// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfEUGcFjOv46gWGD8wCGepp0glLq3Q8vU',
    appId: '1:1036697423454:web:b53a1c9413f05a548beecf',
    messagingSenderId: '1036697423454',
    projectId: 'send-4f919',
    authDomain: 'send-4f919.firebaseapp.com',
    storageBucket: 'send-4f919.appspot.com',
    measurementId: 'G-G3TN9MYPYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHeeBGPeQgms260Tty5cxrVA2aKNBxqFg',
    appId: '1:1036697423454:android:f509f13fdb8b52688beecf',
    messagingSenderId: '1036697423454',
    projectId: 'send-4f919',
    storageBucket: 'send-4f919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARE87se-2x6AJuwe5p2szztywr-JqEBGA',
    appId: '1:1036697423454:ios:04b4e9e9b3423d748beecf',
    messagingSenderId: '1036697423454',
    projectId: 'send-4f919',
    storageBucket: 'send-4f919.appspot.com',
    iosBundleId: 'com.example.send',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARE87se-2x6AJuwe5p2szztywr-JqEBGA',
    appId: '1:1036697423454:ios:32706f6c240d09ba8beecf',
    messagingSenderId: '1036697423454',
    projectId: 'send-4f919',
    storageBucket: 'send-4f919.appspot.com',
    iosBundleId: 'com.example.send.RunnerTests',
  );
}
